language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1

addons:
    apt:
        packages:
            - language-pack-en
            - language-pack-sv

before_script:
  - make deps-install

script:
  - make coverage
  - make cs-check
